---
clickhouse:
  hosts:
    clickhouse01:
      ansible_host: 93.77.187.240

vector:
  hosts:
    vector01:
      ansible_host: 84.252.139.176

lighthouse:
  hosts:
    lighthouse01:
      ansible_host: 158.160.220.98
